apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-deployment
spec:
  selector:
    matchLabels:
      app: skaffold-sample
  template:
    metadata:
      labels:
        app: skaffold-sample
    spec:
      containers:
      - name: skaffold-container
        image: skaffold-sample:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
